return {
  {
    "nvimdev/dashboard-nvim",
    event = "VimEnter",
    opts = {
      theme = "doom",
      config = {
        header = {
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "  █████╗  ██╗      ███████╗",
          " ██╔══██╗ ██║      ██╔════╝",
          " ███████║ ██║      ██║     ",
          " ██╔══██║ ██║      ██████╗ ",
          " ██║  ██║ ██║      ██╔══╝  ",
          " ██║  ██║ ██║      ██║     ",
          " ██║  ██║ ███████╗ ██║     ",
          " ╚═╝  ╚═╝ ╚══════╝ ╚═╝     ",
          "",
          "          /\\_/\\  /\\_/\\         ",
          "         ( o.o )( o.o )        ",
          "          > ^ <---> ^ <        ",
          "         /|   |    |   |\\      ",
          "        (_|   |    |   |_)     ",
          "",
          "   systems that don't page you at 2am   ",
          "",
        },
        center = {
          { icon = "  ", desc = "Find File          ", key = "f", action = "Telescope find_files" },
          { icon = "  ", desc = "Recent Files       ", key = "r", action = "Telescope oldfiles" },
          { icon = "  ", desc = "Find Word          ", key = "g", action = "Telescope live_grep" },
          { icon = "  ", desc = "New File           ", key = "n", action = "ene | startinsert" },
          { icon = "  ", desc = "Config             ", key = "c", action = "edit ~/.config/nvim-fresh/lua" },
          { icon = "  ", desc = "Quit               ", key = "q", action = "qa" },
        },
        footer = { "", "「 keep going 】" },
      },
    },
  },
}
